-- Derive per-surface verification status from scenario evidence + plan claims.
-- @include verification_from_scenarios/00_inputs_normalization.sql
-- @include verification_from_scenarios/10_behavior_assertion_eval.sql
-- @include verification_from_scenarios/20_coverage_reasoning.sql
-- @include verification_from_scenarios/30_rollups_output.sql
